# Generated by Django 2.2.6 on 2019-10-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('rua', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=250)),
                ('cidade', models.CharField(max_length=250)),
                ('ponto_referencia', models.CharField(max_length=250)),
                ('descricao', models.TextField()),
                ('status', models.SmallIntegerField()),
            ],
        ),
    ]
