# Generated by Django 2.2.6 on 2019-10-09 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('senha', models.CharField(max_length=25)),
                ('nascimento', models.DateTimeField()),
                ('status', models.SmallIntegerField()),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_insc', models.DateTimeField()),
                ('evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_eventos.Eventos')),
                ('pessoa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_eventos.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=500)),
                ('data', models.DateTimeField()),
                ('pessoa_evento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_eventos.PessoaEvento')),
            ],
        ),
        migrations.AddField(
            model_name='eventos',
            name='pessoa_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_eventos.Pessoa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventos',
            name='tipo_evento_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_eventos.EventoTipo'),
            preserve_default=False,
        ),
    ]
