# Generated by Django 2.2.6 on 2019-10-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0002_auto_20191009_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='bairro',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='data_fim',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='tipo_evento_id',
            new_name='eventType',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='cidade',
            new_name='neighborhood',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='ponto_referencia',
            new_name='referencePoint',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='data_inicio',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='rua',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='eventotipo',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='nascimento',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='senha',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='sexo',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='nome',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='eventos',
            name='status',
            field=models.BooleanField(),
        ),
    ]
