# Generated by Django 2.2.6 on 2019-10-17 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0003_auto_20191010_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='password',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
