# Generated by Django 2.2.6 on 2019-10-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0005_auto_20191017_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='username',
            new_name='user',
        ),
    ]
