# Generated by Django 2.2.6 on 2019-10-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0006_auto_20191018_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='user',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='username',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
