# Generated by Django 2.2.6 on 2019-10-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0007_auto_20191018_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
