# Generated by Django 2.2.6 on 2019-10-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0008_auto_20191018_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='username',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
