# Generated by Django 2.2.6 on 2019-10-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0009_auto_20191018_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
