# Generated by Django 2.2.6 on 2019-11-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0010_auto_20191018_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='birthdate',
            field=models.DateTimeField(),
        ),
    ]
