# Generated by Django 2.2.6 on 2019-11-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0011_auto_20191108_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
