# Generated by Django 2.2.6 on 2019-11-08 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0012_auto_20191108_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='pessoa_id',
            new_name='user',
        ),
    ]
