# Generated by Django 2.2.6 on 2019-11-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0013_auto_20191108_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoaevento',
            old_name='evento_id',
            new_name='eventoId',
        ),
        migrations.RenameField(
            model_name='pessoaevento',
            old_name='pessoa_id',
            new_name='participantId',
        ),
        migrations.RenameField(
            model_name='pessoaevento',
            old_name='data_insc',
            new_name='subscriptionDate',
        ),
    ]
