# Generated by Django 2.2.6 on 2019-11-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0014_auto_20191110_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='data',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='mensagem',
            old_name='mensagem',
            new_name='messageDate',
        ),
        migrations.RenameField(
            model_name='mensagem',
            old_name='pessoa_evento_id',
            new_name='participantId',
        ),
    ]
