# Generated by Django 2.2.6 on 2019-11-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0015_auto_20191110_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='messageDate',
            field=models.DateTimeField(),
        ),
    ]
