# Generated by Django 2.2.6 on 2019-11-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0016_auto_20191110_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pessoaevento',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
