# Generated by Django 2.2.6 on 2019-11-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0017_auto_20191110_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
