# Generated by Django 2.2.6 on 2019-11-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0019_auto_20191110_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
