# Generated by Django 2.2.6 on 2019-11-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0020_auto_20191110_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoaevento',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
