# Generated by Django 2.2.6 on 2019-11-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0021_auto_20191111_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
