# Generated by Django 2.2.6 on 2019-11-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0022_auto_20191111_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoaevento',
            old_name='participantId',
            new_name='userId',
        ),
    ]
