# Generated by Django 2.2.6 on 2019-11-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0023_auto_20191112_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoaevento',
            old_name='subscriptionDate',
            new_name='registrationDate',
        ),
    ]
