# Generated by Django 2.2.6 on 2019-11-12 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0024_auto_20191112_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='eventoId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_eventos.Eventos'),
            preserve_default=False,
        ),
    ]
