# Generated by Django 2.2.6 on 2019-11-12 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_eventos', '0026_remove_mensagem_participantid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='participantId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_eventos.PessoaEvento'),
            preserve_default=False,
        ),
    ]
